services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  rag_bot:
    build: .
    container_name: rag_bot
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LLM_KEY=${LLM_KEY}
      - BOT_KEY=${BOT_KEY}
      - BASE_URL=${BASE_URL}
    restart: unless-stopped
    runtime: nvidia
