version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app-network

  rag_bot:
    build: .
    container_name: rag_bot
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LLM_KEY=${LLM_KEY}
      - BOT_KEY=${BOT_KEY}
      - BASE_URL=${BASE_URL}
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge